name: '🚀 Build and Publish jellyfin-docs'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/*.json'

jobs:
  build_publish:
    uses: jellyfin/jellyfin-docs/.github/workflows/_meta.yaml@master
    with:
      publish: true
